### ISSUE TITLE
Can't run `info` on tags: unknown tag version

### ISSUE THREAD

**Issue by jdmwood** [kong-org/halo-eth-cli#2]
Hi there, 

I'm trying to run `node cli.js info` and I'm getting an error.

```
Error: Unknown tag version!
    at cb (/Users/john/3rdParty/halo-eth-cli/cli.js:234:19)
    at async ACR122Reader.<anonymous> (/Users/john/3rdParty/halo-eth-cli/cli.js:515:19)
NFC card or compatible PC/SC reader not found.
```

The tag version seems to be `0x73` on our chips and the reason it fails is because of a timeout. I tried increasing the timeout to 10 seconds but it still times out. Any ideas?

**Comment by ccamrobertson** [comment]
@jdmwood this is expected as the chips shipped today are "v1" chips and don't support this command. We are working on documentation for the v2 chips which we should stock shortly (all chips in 2023 will be "v2" chips); they include a few extras however the core interface is the same. The `info` command is available in these v2 chips.

**Comment by jdmwood** [comment]
@ccamrobertson Thanks so much for the clarification!
